# appveyor.yml  —  runs Downloads.bat → show.bat → loop.bat

version: 1.0.{build}

# Use the newest Windows image (Server 2019 + VS 2022 toolchain)
image: Visual Studio 2022      # other options: Visual Studio 2019, 2017, …

# ───────────────────────────────────────────
# Build-phase scripts
# ───────────────────────────────────────────
build_script:
  # 1  Download and install essentials
  - ps: |
      Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" `
                        -OutFile "Downloads.bat"
  - cmd: Downloads.bat

  # 2  Show Website
  - cmd: show.bat

  # 3  Time Counter (runs until script exits or job times-out)
  - cmd: loop.bat

# ───────────────────────────────────────────
# (Optional) increase job timeout in UI or BYOC
# ───────────────────────────────────────────
# AppVeyor’s hosted VMs have a 60-minute hard limit; ask support to
# raise it to 120 min, or switch to a self-hosted/Bring-Your-Own-Cloud
# runner for the full 360 min you need.

